blank_issues_enabled: false
contact_links:
  - name: Instagram
    url: https://instagram.com/madmax4708/
    about: Questions asked on the group usually get answered faster.
  - name: Twitter
    url: https://twitter.com/503_madmax
    about: You can also contact us on FaceBook(HackWeiser360)
